package com.sltx.entity.model;

import io.jboot.db.annotation.Table;

import com.sltx.entity.model.base.BaseData;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_data", primaryKey = "id")
public class Data extends BaseData<Data> {
	
}
