package com.sltx.entity.model;

import io.jboot.db.annotation.Table;

import com.sltx.entity.model.base.BaseRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_res", primaryKey = "id")
public class Res extends BaseRes<Res> {
	
}
