package com.sltx.entity.model;

import io.jboot.db.annotation.Table;

import com.sltx.entity.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class Role extends BaseRole<Role> {
	
}
