package com.sltx.entity.model;

import io.jboot.db.annotation.Table;

import com.sltx.entity.model.base.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
